package com.example.unina.myfcar.Configurazione;

public enum NomeSerie {
    POSIZIONE_ORIZZONTALE_SEDILE, INCLINAZIONE_SEDILE, ANGOLO_AZIMUTALE_SPECCHIETTO_DX, ANGOLO_ZENITALE_SPECCHIETTO_DX, ANGOLO_AZIMUTALE_SPECCHIETTO_SX, ANGOLO_ZENITALE_SPECCHIETTO_SX, TEMPERATURA, FREQUENZA_STAZIONE_RADIO_1, FREQUENZA_STAZIONE_RADIO_2, FREQUENZA_STAZIONE_RADIO_3, FREQUENZA_STAZIONE_RADIO_4, FREQUENZA_STAZIONE_RADIO_5, FREQUENZA_STAZIONE_RADIO_6;

}
